### ISSUE TITLE
How to deploy in Vercel？

### ISSUE THREAD

**Issue by Cxyofficial** [structuraBlock/structuraBlock.github.io#3]

**Comment by structuraBlock** [comment]
belike a normal web app
    
    or show me the error?

**Comment by Cxyofficial** [comment]
Thanks,I've already deployed with Github Pages,your project is very useful,I will give you a star👍



---Original---
From: ***@***.***&gt;
Date: Sat, Aug 10, 2024 18:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [structuraBlock/structuraBlock.github.io] How to deploy in Vercel？ (Issue #3)




 belike a normal web app or show me the error?
